### ISSUE TITLE
Suggestion for auto ban detection of bots

### ISSUE THREAD

**Issue by JONTTM** [leighmacdonald/gbans#110] opened 2021-06-17 07:42 UTC
Quote from Kaiga:
> A plugin that bans multiple users connecting from the same IP, and also autobans anyone who uses newline characters in the chat seems like a bit of a no-brainer.

**Comment by JONTTM** [comment] 2021-06-19 10:11
At least 4-5 bot raids in the past 48 hours on Uncletopia

**Comment by leighmacdonald** [comment] 2021-10-04 17:31
Duplicate of #140

**Closed by leighmacdonald** 2021-10-04 17:31 UTC
